#weight_init: kaiming_normal
#score_init: None
dataset: imdb
weight_seed: 0
score_seed: 0
gpu: 6

model_type: 'Dense'
#weight_file: /s/luffy/b/nobackup/mgorb/weights/dense.pt

weight_file: dense_nlp.pt