#weight_init: kaiming_normal
#score_init: None
dataset: Heartbeat

weight_seed: 0
score_seed: 0
gpu: 2
batch_size: 8
model_type: 'Dense'
#weight_file: /s/luffy/b/nobackup/mgorb/weights/dense.pt
epochs: 50
weight_file: dense_ts_smd

nhid: 128
dmodel: 128
save_scores: False
layer_norm: False
batch_norm: True
save_graphs: False

pos_enc: 'Learnable'
