prune_rate: 0.01
lin_prune_rate: 0.5
#weight_init: kaiming_normal
#score_init: None
weight_seed: 0
score_seed: 0
gpu: 6
epochs: 20
model_type: 'SparseBinary'
weight_file: sb_weight.pt
#weight_file: weights/sb_weight.pt