
dataset: SMAP

weight_seed: 0
score_seed: 0
gpu: 1
batch_size: 128

model_type: 'Sparse'

attention: 'Dense' #

layer_norm_prune_rate: 0.5
lin_prune_rate: 0.5
attention_prune_rate: .5

epochs: 50
weight_file: dense_ts_smd

window_size: 50
forecast: True
save_scores: False
layer_norm: False
batch_norm: False
save_graphs: False

pos_enc: 'Standard'

