#weight_init: kaiming_normal
#score_init: None
dataset: electricity

weight_seed: 0
score_seed: 0
gpu: 2
batch_size: 128

model_type: 'Sparse'
attention: 'Dense'

epochs: 50
weight_file: sparse_ts_electricity

layer_norm_prune_rate: 0.5
lin_prune_rate: 0.5
attention_prune_rate: .5
has_src_mask: True

window_size: 200
dmodel: 512
forecast: True
save_scores: False
layer_norm: False
batch_norm: True
save_graphs: False

pos_enc: 'Standard'
lr: .001
scheduler: True


