prune_rate: 0.2
#weight_init: kaiming_normal
#score_init: None
weight_seed: 0
score_seed: 0
gpu: 6

model_type: 'SparseBinary'
weight_file: /s/luffy/b/nobackup/mgorb/weights/sb_weight.pt
#weight_file: weights/sb_weight.pt