#weight_init: kaiming_normal
#score_init: None
dataset: SelfRegulationSCP1

weight_seed: 0
score_seed: 0
gpu: 3
batch_size: 8

model_type: 'Sparse'
attention: 'Sparse' #

layer_norm_prune_rate: 0.5
lin_prune_rate: 0.5
attention_prune_rate: .5
#weight_init: 'kaiming_normal'
#scale_fan: False

epochs: 100
weight_file: sparse_cls_scp

nhid: 256
dmodel: 128
n_layers: 2
n_head: 2
save_scores: False
layer_norm: False
batch_norm: False
save_graphs: False
lr: 1e-3
pos_enc: 'Fixed'