dataset: imdb
#emb_prune_rate: 0.03
layer_norm_prune_rate: 0.5
lin_prune_rate: 0.5
attention_prune_rate: .05


#weight_init: kaiming_normal
#score_init: None
weight_seed: 0
score_seed: 0
gpu: 6
epochs: 20
model_type: 'SparseBinary'
weight_file: sb_weight_nlp.pt
#weight_file: weights/sb_weight.pt