#weight_init: kaiming_normal
#score_init: None
emb_prune_rate: 0.03
layer_norm_prune_rate: 0.5
lin_prune_rate: 0.5
attention_prune_rate: .05

dataset: SMD
weight_seed: 0
score_seed: 0
gpu: 6
batch_size: 128
model_type: 'Sparse'
#weight_file: /s/luffy/b/nobackup/mgorb/weights/dense.pt
epochs: 250
weight_file: sparse_ts_smd.pt

window_size: 100
forecast: True
save_scores: True