#weight_init: kaiming_normal
#score_init: None
dataset: InsectWingbeat

weight_seed: 0
score_seed: 0
gpu: 2
batch_size: 8

model_type: 'Sparse'
attention: 'SparseTopP' #

layer_norm_prune_rate: 0.5
lin_prune_rate: 0.5
attention_prune_rate: .5
#weight_init: 'kaiming_normal'
#scale_fan: False

epochs: 250
weight_file: sparse_cls_insect

nhid: 256
n_layers: 3
n_head: 8
dmodel: 64
save_scores: False
layer_norm: False
batch_norm: True
save_graphs: False
lr: 1e-4
pos_enc: 'Learnable'